apiVersion: v1
kind: Secret
metadata:
  name: pictionary-db-secret
  namespace: pictionary
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "<REMPLACER_root_password>"
  MYSQL_DATABASE: "pictionary"
  MYSQL_USER: "<REMPLACER_user>"
  MYSQL_PASSWORD: "<REMPLACER_user_password>"
